GET http://localhost:8000/usersdata
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImFuamFyeUBnbWFpbC5jb20iLCJGaXJzdF9uYW1lIjoiUmFqYW9uYXJpc29uIiwiTGFzdF9uYW1lIjoiQW5qYXJ5IiwiVWlkIjoiNjY3MDA0YTk5ZGQwOWUxZDI2ZWNhZjVlIiwiVXNlcl90eXBlIjoiVVNFUiIsImV4cCI6MTcxODcwMzY1N30.0M2xEgHMTLCygy84MJ017mMQPd5nN3ww3w9C1-4yaXU